r=raspi;
freq=50;
Motor1=12;
Motor2=20;
Motor3=16;
Motor4=17;
Motor5=27;
Motor6=22;
configurePin(r,Motor1,'PWM')
configurePin(r,Motor2,'PWM')
configurePin(r,Motor3,'PWM')
configurePin(r,Motor4,'PWM')
configurePin(r,Motor5,'PWM')
configurePin(r,Motor6,'PWM')
writePWMFrequency(r,Motor1,freq)
writePWMFrequency(r,Motor2,freq)
writePWMFrequency(r,Motor3,freq)
writePWMFrequency(r,Motor4,freq)
writePWMFrequency(r,Motor5,freq)
writePWMFrequency(r,Motor6,freq)

angles=inv_ken(0,0,23,0,0,0);
duty=Angle2Duty(angles)/20;
writePWMDutyCycle(r,Motor1,duty(1))
writePWMDutyCycle(r,Motor2,duty(2))
writePWMDutyCycle(r,Motor3,duty(3))
writePWMDutyCycle(r,Motor4,duty(4))
writePWMDutyCycle(r,Motor5,duty(5))
writePWMDutyCycle(r,Motor6,duty(6))
